// <auto-generated />
using System;
using MSDF_EFCoreModelApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MSFD_EFCoreModelApp.Migrations
{
    [DbContext(typeof(HRDbContext))]
    partial class HRDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("MSDF_EFCoreModelApp.Models.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DepartmentID");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentID = 1,
                            Name = "HR"
                        },
                        new
                        {
                            DepartmentID = 2,
                            Name = "Engineering"
                        });
                });

            modelBuilder.Entity("MSDF_EFCoreModelApp.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfHire")
                        .HasColumnType("TEXT");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeID = 1,
                            DateOfHire = new DateTime(2025, 12, 15, 20, 3, 40, 502, DateTimeKind.Local).AddTicks(2137),
                            DepartmentID = 1,
                            FirstName = "Aiko",
                            LastName = "Tanaka"
                        },
                        new
                        {
                            EmployeeID = 2,
                            DateOfHire = new DateTime(2025, 12, 15, 20, 3, 40, 504, DateTimeKind.Local).AddTicks(4958),
                            DepartmentID = 2,
                            FirstName = "Zainab",
                            LastName = "Al-Farsi"
                        });
                });

            modelBuilder.Entity("MSDF_EFCoreModelApp.Models.Employee", b =>
                {
                    b.HasOne("MSDF_EFCoreModelApp.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("MSDF_EFCoreModelApp.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
